/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.mockframework;

import org.junit.Test;
import ru.nsu.app.TestClass;

import static org.junit.Assert.*;

public class AppTest {

    @Mock
    private TestClass mock;

    @Test public void testMockAnnotation() {
        JMock.initMocks(this);
        assertEquals(null, mock.getIntAndReturnStrOfGivenInt(5));

        JMock.when(mock.getIntAndReturnStrOfGivenInt(JMock.anyNumerical())).thenReturn("You put smth");
        JMock.when(mock.getIntAndReturnStrOfGivenInt(JMock.eq(10))).thenReturn("You put 10");

        assertEquals("You put 10", mock.getIntAndReturnStrOfGivenInt(10));
        assertEquals("You put smth", mock.getIntAndReturnStrOfGivenInt(555));
    }

    @Test public void testNonStatic() {
        TestClass test = new TestClass();
        assertEquals("1 \0", test.getTwoPrimitiveArgsAndReturnStrOfThem(1, '\0'));

        test = JMock.mock(TestClass.class);
        assertNull(test.getTwoPrimitiveArgsAndReturnStrOfThem(1, '\0'));

        JMock.when(
          test.getTwoPrimitiveArgsAndReturnStrOfThem(JMock.anyNumerical(), JMock.anyChar())
        ).thenReturn("OKAY");
        assertEquals("OKAY", test.getTwoPrimitiveArgsAndReturnStrOfThem(1, '\0'));

        JMock.when(test.getString()).thenReturn("OKAY2");
        assertEquals("OKAY2", test.getString());

        JMock.when(test.getChar()).thenReturn('b');
        assertEquals('b', test.getChar());
        assertEquals("OKAY2", test.getString());
        assertEquals("OKAY", test.getTwoPrimitiveArgsAndReturnStrOfThem(1, '\0'));

        JMock.when(test.getInt()).thenReturn(1);
        assertEquals(1, test.getInt());

        JMock.when(test.getIntArr()).thenReturn(new int[] {5,6,6});
        assertArrayEquals(new int[] {5,6,6}, test.getIntArr());

        JMock.when(test.getTwoPrimitiveArgsAndReturnStrOfThem(JMock.eq(1), JMock.eq('\0'))).thenReturn("OnlyIf1And0");
        assertEquals("OnlyIf1And0", test.getTwoPrimitiveArgsAndReturnStrOfThem(1, '\0'));
        assertEquals("OKAY", test.getTwoPrimitiveArgsAndReturnStrOfThem(0, '\0'));
        assertEquals("OKAY", test.getTwoPrimitiveArgsAndReturnStrOfThem(1, '\n'));
    }

    @Test public void testStatic() {
        assertEquals("TEST STATIC", TestClass.staticGetStr());
        try(StaticMock mock = JMock.makeStaticMock(TestClass.class)) {
            assertNull(TestClass.staticGetStr());
            JMock.when(TestClass.staticGetStr()).thenReturn("TEST MOCK");
            assertEquals("TEST MOCK", TestClass.staticGetStr());
        }
        assertEquals("TEST STATIC", TestClass.staticGetStr());
    }
}
