/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.nsu.app;

import javassist.ClassPool;
import javassist.CtClass;
import javassist.Modifier;
import ru.nsu.mockframework.JMock;
import ru.nsu.mockframework.Mock;


public class App {

  @Mock
  private static TestClass kektest;

  private static void test() {
    JMock.removeFinals(TestClass.class); //TODO mb make it better
    TestClass test = new TestClass();
    System.out.println(test.testString());
    test = JMock.mock(TestClass.class);
    System.out.println(test.testString() + " called from .mock");
    JMock.initMocks(App.class);
    System.out.println(kektest.testString() + " called from initMocks");
    JMock.when(kektest.testString()).thenReturn("mock");
    System.out.println(kektest.testString());
    JMock.when(kektest.testInt()).thenReturn(228);
    System.out.println(kektest.testInt());
    JMock.when(kektest.testString()).thenReturn("22");
  }

  public static void main(String[] args) {

    test();
  }
}
